title: Cuba Freedom
description: "Blog about the situation in Cuba – Noticias y opiniones."
baseurl: ""
url: "https://cubafreedom.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
languages: ["en", "es"]
default_lang: "en"
paginate: 5
paginate_path: "/page:num/"
